Allow kylekatarnls/update-helper to fix CI
Error:
Error: kylekatarnls/update-helper contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
You can run "composer config --no-plugins allow-plugins.kylekatarnls/update-helper [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)
See https://getcomposer.org/allow-plugins
In PluginManager.php line 762:
  kylekatarnls/update-helper contains a Composer plugin which is blocked by y
  our allow-plugins config. You may add it to the list if you consider it saf
  e.
  You can run "composer config --no-plugins allow-plugins.kylekatarnls/update
  -helper [true|false]" to enable it (true) or disable it explicitly and supp
  ress this exception (false)
  See https://getcomposer.org/allow-plugins