Drop PHP 7.2 support and update phpunit (#966)
* Drop PHP 7.2 support and update phpunit

* Update test matrix (PHP-Laravel versions)

* Allow kylekatarnls/update-helper to fix CI

Error:
Error: kylekatarnls/update-helper contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
You can run "composer config --no-plugins allow-plugins.kylekatarnls/update-helper [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)
See https://getcomposer.org/allow-plugins
In PluginManager.php line 762:
  kylekatarnls/update-helper contains a Composer plugin which is blocked by y
  our allow-plugins config. You may add it to the list if you consider it saf
  e.
  You can run "composer config --no-plugins allow-plugins.kylekatarnls/update
  -helper [true|false]" to enable it (true) or disable it explicitly and supp
  ress this exception (false)
  See https://getcomposer.org/allow-plugins

* Skip failing matrix element

PHPUnit 9.0.0 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.0.20
Configuration: /home/runner/work/telegram-bot-sdk/telegram-bot-sdk/phpunit.xml.dist
  Warning - The configuration file did not pass validation!
  The following problems have been detected:
  Line 14:
  - Element 'coverage': This element is not expected.
  Test results may not be as expected.
PHP Fatal error:  Type declaration 'mixed' must be unqualified in /home/runner/work/telegram-bot-sdk/telegram-bot-sdk/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 323
......................................................
Error: Process completed with exit code 255.

* Update phpunit version